export const COLOR_ELECTRIC_INDIGO = '#fe3c72';
export const COLOR_INTERDIMENSIONAL_BLUE = '#3700B3';
export const COLOR_ROBIN_EGG_BLUE = '#03DAC6';
export const COLOR_DARK_CYAN = '#018786';
export const COLOR_WHITE = '#FFFFFF';
export const COLOR_ERROR_RED = '#B00020';
export const COLOR_BLACK = '#000000';
export const COLOR_GREY = '#808080';

export const COLOR_PRIMARY = COLOR_ELECTRIC_INDIGO;
export const COLOR_PRIMARY_VARIANT = COLOR_INTERDIMENSIONAL_BLUE;
export const COLOR_SECONDARY = COLOR_ROBIN_EGG_BLUE;
export const COLOR_SECONDARY_VARIANT = COLOR_DARK_CYAN;

export const COLOR_BACKGROUND = COLOR_BLACK;
export const COLOR_SURFACE = COLOR_BLACK;
export const COLOR_TEXT_PRIMARY = COLOR_WHITE;
export const COLOR_TEXT_SECONDARY = COLOR_GREY;
