export const COLOR_RADICAL_RED = '#FF7158';
export const COLOR_PANTONE = '#FD2B7B';
export const COLOR_CHARCOAL = '#424242';
export const COLOR_DARK_CYAN = '#808080';
export const COLOR_WHITE = '#FFFFFF';
export const COLOR_ERROR_RED = '#B00020';
export const COLOR_BLACK = '#000000';

export const COLOR_PRIMARY = COLOR_RADICAL_RED;
export const COLOR_PRIMARY_VARIANT = COLOR_PANTONE;
export const COLOR_SECONDARY = COLOR_CHARCOAL;
export const COLOR_SECONDARY_VARIANT = COLOR_DARK_CYAN;

export const COLOR_BACKGROUND = COLOR_BLACK;
export const COLOR_SURFACE = COLOR_BLACK;
